
drop table [dbo].[BillingConfigsRaw]
drop table [dbo].[BillingConfigEdi]
drop table [dbo].[BillingConfigMatchCriteria]
drop table [dbo].[BillingConfigs]
drop table [dbo].[BillingConfigSCAs]
drop table [dbo].[BillingConfigSigners]
drop table [dbo].[BillingConfigSourceLocations]
drop table [dbo].[BillingConfigFacilities]
drop table [dbo].[DataMigrationMessages]
drop table [dbo].[EDI_HSEDICustomerConfigData_PROJECTS]
drop table [dbo].[MissingLicenses]
drop table [dbo].[MissingStatesAndProvinces]
drop table [dbo].[ProspectContacts]
drop table [dbo].[ProspectContactsTemp]
drop table [dbo].[ProspectContactEmailPhones]
drop table [dbo].[Contact_Person]
drop table [dbo].[Contact_Person_Electronic_Address]
drop table [dbo].[Contact_Person_Postal_Address]
drop table [dbo].[Customers]
drop table [dbo].[Customers_Electronic_Addresses]
drop table [dbo].[Customers_Postal_Addresses]
drop table [dbo].[Customers_operator_code]
drop table [dbo].[EDI_Customer_Additional_Pref]
drop table [dbo].[EDI_Customer_Additional_Pref_Field_Tickets]
drop table [dbo].[EDI_HSEDICustomerConfigEntity]
drop table [dbo].[EDI_HSEDICustomerConfigEntity_SCA]
drop table [dbo].[EDI_HSEDICustomerConfigMasterEntity]
drop table [dbo].[EdiFieldDefinitions]
drop table [dbo].[FacilityMappings]
drop table [dbo].[FacilityServiceSpartanParameters]
drop table [dbo].[FacilityTank]
drop table [dbo].[InvoiceConfigs]
drop table [dbo].[LegalEntity]
drop table [dbo].[Non_Billable_Customers]
drop table [dbo].[Non_Billable_Customers_Electronic_Address]
drop table [dbo].[Non_Billable_Customers_Postal_Address]
drop table [dbo].[Products_Released]
drop table [dbo].[ProductVariants]
drop table [dbo].[Prospect_Electronic_Address]
drop table [dbo].[Prospect_Postal_Address]
drop table [dbo].[Prospects]
drop table [dbo].[SCA]
drop table [dbo].[Sites]
drop table [dbo].[SourceLocationTypes]
drop table [dbo].[SpartanProductParameters]
drop table [dbo].[TankTypes]
drop table [dbo].[TradeAgreement]
drop table [dbo].[AccountMaster]
drop table [dbo].[SourceLocations]
drop table [dbo].[uwi]
drop table [dbo].[ProductCategories]
drop table [dbo].[ProductItemCategories]
drop table [dbo].ValidCustomerAccounts;
drop table [dbo].ContactFunctions;

GO



--only drop if re-importing
--drop table [dbo].[ProductCategoriesImport]
--Used if excange will be seeded on the fly from here
--drop table [dbo].[InvoiceExchangeMappings]
--drop table [dbo].[InvoiceExchangeMappingsTemp]